### ISSUE TITLE
БЭМ, компонентность

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/hotel-webpack-pug-scss#2]
Все блоки реализовать в виде миксинов.
![Снимок экрана от 2019-12-03 13-27-12](https://user-images.githubusercontent.com/36810364/70042877-b575d280-15d0-11ea-9368-984795fb4981.png)

Имя папки где лежит миксин, имя миксина и имя блока в миксине должны совпадать.
![Снимок экрана от 2019-12-03 13-26-01](https://user-images.githubusercontent.com/36810364/70042788-8b241500-15d0-11ea-9c4e-ea4f5166047c.png)

Поправить по всему проекту.

**Comment by EvgeniyChuprov** [comment]
Тут миксин содержит 2 разных блока.
![Снимок экрана от 2019-12-06 13-20-18](https://user-images.githubusercontent.com/36810364/70315703-39c39200-182b-11ea-8bba-a416b5340072.png)

**Comment by EvgeniyChuprov** [comment]
Миксин не должен вызывать сам себя.
![Снимок экрана от 2019-12-06 13-25-35](https://user-images.githubusercontent.com/36810364/70316077-f0c00d80-182b-11ea-944b-566332398642.png)

Структура страницы должна быть древовидная. Те страница должна содержать основной блок
и передавать в него все параметры. Этот блок уже содержит в себе блоки помельче и передает в них необходимые им данные, полученные с основной страницы, те в свою очередь содержат более мелкие блоки и так далее.

**Comment by EvgeniyChuprov** [comment]
Что это? Если модификатор, то он оформляется не так. 
![Снимок экрана от 2019-12-12 16-58-13](https://user-images.githubusercontent.com/36810364/70718123-b1e4f880-1d00-11ea-9e89-3647200b812e.png)

Два блока в миксине. Не единичный слуучай
![Снимок экрана от 2019-12-12 17-09-02](https://user-images.githubusercontent.com/36810364/70718907-2c624800-1d02-11ea-866d-43ccf8dcfefe.png)

Использовать числа в названиях не хорошо.
![Снимок экрана от 2019-12-12 17-10-08](https://user-images.githubusercontent.com/36810364/70719011-5a478c80-1d02-11ea-8b6d-645e60971d55.png)

**Comment by EvgeniyChuprov** [comment]
inner наверное не модификатор, а элемент?
![image](https://user-images.githubusercontent.com/36810364/71468551-7144af00-27d7-11ea-991c-747a27bb0bd3.png)
числа в названиях до сих пор встречаются
![Снимок экрана от 2019-12-26 12-02-40](https://user-images.githubusercontent.com/36810364/71468632-b79a0e00-27d7-11ea-80e1-4c193401801e.png)

**Comment by EvgeniyChuprov** [comment]
[Изучи внимательно модификаторы БЭМ и разбери примеры](https://ru.bem.info/methodology/quick-start/#модификатор)
![Снимок экрана от 2020-01-10 13-10-22](https://user-images.githubusercontent.com/36810364/72144997-9d9d2580-33aa-11ea-9cbd-918715962feb.png)
Модификатор нельзя использовать самостоятельно
В первой строке у тебя вообще 2 модификатора на одном элементе, причем один из них для элемента, а второй для блока, но ни одной из этих сущностей нет.

**Comment by EvgeniyChuprov** [comment]
Именование классов должно быть осмысленным.
И снова блок внутри блока.
![Снимок экрана от 2020-01-15 13-19-53](https://user-images.githubusercontent.com/36810364/72425938-d0c02a00-3799-11ea-9fd0-85e2c952b774.png)
![Снимок экрана от 2020-01-15 13-31-53](https://user-images.githubusercontent.com/36810364/72426780-6b6d3880-379b-11ea-9e8a-1edeb0cc0088.png)

**Comment by EvgeniyChuprov** [comment]
![Снимок экрана от 2020-01-15 13-41-31](https://user-images.githubusercontent.com/36810364/72427431-c8b5b980-379c-11ea-864c-34d348630dae.png)
Параметры в миксины должны приходить снаружи.
Cлишком большая длина строки, в стандартах airbnb есть.

**Comment by Vodkamishka** [comment]
> Все блоки реализовать в виде миксинов.
> ![Снимок экрана от 2019-12-03 13-27-12](https://user-images.githubusercontent.com/36810364/70042877-b575d280-15d0-11ea-9368-984795fb4981.png)
> 
> Имя папки где лежит миксин, имя миксина и имя блока в миксине должны совпадать.
> ![Снимок экрана от 2019-12-03 13-26-01](https://user-images.githubusercontent.com/36810364/70042788-8b241500-15d0-11ea-9c4e-ea4f5166047c.png)
> 
> Поправить по всему проекту.

Исправил

**Comment by Vodkamishka** [comment]
> Тут миксин содержит 2 разных блока.
> ![Снимок экрана от 2019-12-06 13-20-18](https://user-images.githubusercontent.com/36810364/70315703-39c39200-182b-11ea-8bba-a416b5340072.png)

исправил

**Comment by Vodkamishka** [comment]
> Миксин не должен вызывать сам себя.
> ![Снимок экрана от 2019-12-06 13-25-35](https://user-images.githubusercontent.com/36810364/70316077-f0c00d80-182b-11ea-944b-566332398642.png)
> 
> Структура страницы должна быть древовидная. Те страница должна содержать основной блок
> и передавать в него все параметры. Этот блок уже содержит в себе блоки помельче и передает в них необходимые им данные, полученные с основной страницы, те в свою очередь содержат более мелкие блоки и так далее.

исправил

**Comment by Vodkamishka** [comment]
> Что это? Если модификатор, то он оформляется не так.
> ![Снимок экрана от 2019-12-12 16-58-13](https://user-images.githubusercontent.com/36810364/70718123-b1e4f880-1d00-11ea-9e89-3647200b812e.png)
> 
> Два блока в миксине. Не единичный слуучай
> ![Снимок экрана от 2019-12-12 17-09-02](https://user-images.githubusercontent.com/36810364/70718907-2c624800-1d02-11ea-866d-43ccf8dcfefe.png)
> 
> Использовать числа в названиях не хорошо.
> ![Снимок экрана от 2019-12-12 17-10-08](https://user-images.githubusercontent.com/36810364/70719011-5a478c80-1d02-11ea-8b6d-645e60971d55.png)

исправил

**Comment by Vodkamishka** [comment]
> inner наверное не модификатор, а элемент?
> ![image](https://user-images.githubusercontent.com/36810364/71468551-7144af00-27d7-11ea-991c-747a27bb0bd3.png)
> числа в названиях до сих пор встречаются
> ![Снимок экрана от 2019-12-26 12-02-40](https://user-images.githubusercontent.com/36810364/71468632-b79a0e00-27d7-11ea-80e1-4c193401801e.png)
> Снова модификаторы сами по себе висят
> ![Снимок экрана от 2019-12-26 12-17-37](https://user-images.githubusercontent.com/36810364/71469290-c08bdf00-27d9-11ea-9744-101221c87507.png)

исправил

**Comment by Vodkamishka** [comment]
> ![Снимок экрана от 2020-01-15 13-41-31](https://user-images.githubusercontent.com/36810364/72427431-c8b5b980-379c-11ea-864c-34d348630dae.png)
> Параметры в миксины должны приходить снаружи.
> Cлишком большая длина строки, в стандартах airbnb есть.

исправил

**Comment by Vodkamishka** [comment]
> [Изучи внимательно модификаторы БЭМ и разбери примеры](https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80)
> ![Снимок экрана от 2020-01-10 13-10-22](https://user-images.githubusercontent.com/36810364/72144997-9d9d2580-33aa-11ea-9cbd-918715962feb.png)
> Модификатор нельзя использовать самостоятельно
> В первой строке у тебя вообще 2 модификатора на одном элементе, причем один из них для элемента, а второй для блока, но ни одной из этих сущностей нет.
> Встречается во всем проекте.

исправил

**Comment by Vodkamishka** [comment]
> Именование классов должно быть осмысленным.
> И снова блок внутри блока.
> ![Снимок экрана от 2020-01-15 13-19-53](https://user-images.githubusercontent.com/36810364/72425938-d0c02a00-3799-11ea-9fd0-85e2c952b774.png)
> ![Снимок экрана от 2020-01-15 13-31-53](https://user-images.githubusercontent.com/36810364/72426780-6b6d3880-379b-11ea-9e8a-1edeb0cc0088.png)

исправил

**Comment by EvgeniyChuprov** [comment]
Тут поправишь и можешь закрыть.
![Снимок экрана от 2020-02-24 13-25-16](https://user-images.githubusercontent.com/36810364/75144952-22e55b00-5709-11ea-80a2-29d550ec6fb3.png)

**Comment by Vodkamishka** [comment]
> Тут поправишь и можешь закрыть.
> ![Снимок экрана от 2020-02-24 13-25-16](https://user-images.githubusercontent.com/36810364/75144952-22e55b00-5709-11ea-80a2-29d550ec6fb3.png)

исправил
