### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/hotel-webpack-pug-scss#4]
Переписать js на классы ES6.
Код должен соответствовать стандартам fsd и стайлгайду AirBnB, в том числе и по оформлению. Никаких var, ++ и так далее. Лучше поставить ESlint и настроить его на правила AirBnB.

Календарь работает не правильно. При указании интервала дат, прибытие и выезд сейчас указываются в одной ячейке.
![image](https://user-images.githubusercontent.com/36810364/70314564-c3259500-1828-11ea-9ec6-40b7829d0efc.png)

**Comment by EvgeniyChuprov** [comment]
Js- код компонента должен располагаться в нем же а не импортироваться от куда то.
Если используется библиотека, она подключается в начале этого файла.
![Снимок экрана от 2019-12-14 12-37-48](https://user-images.githubusercontent.com/36810364/70846831-93047480-1e6e-11ea-9752-ba5a92c5620f.png)

Весь код в js писать на классах.

**Comment by EvgeniyChuprov** [comment]
Сейчас все подтягивается директивами @import, что конечно имеет право на жизнь, но такое решение содержит ряд недостатков. Каждый раз при подключении-отключении блока нужно делать импорт руками добавляя это все. Нужно сделать функцию в точке входа (index.js), которая будет собирать все твои стилевые файлы, картинки, js и т. д. Тогда все импорты  можно убрать

**Comment by Vodkamishka** [comment]
> Переписать js на классы ES6.
> Код должен соответствовать стандартам fsd и стайлгайду AirBnB, в том числе и по оформлению. Никаких var, ++ и так далее. Лучше поставить ESlint и настроить его на правила AirBnB.
> 
> Календарь работает не правильно. При указании интервала дат, прибытие и выезд сейчас указываются в одной ячейке.
> ![image](https://user-images.githubusercontent.com/36810364/70314564-c3259500-1828-11ea-9ec6-40b7829d0efc.png)

исправил

**Comment by Vodkamishka** [comment]
> Js- код компонента должен располагаться в нем же а не импортироваться от куда то.
> Если используется библиотека, она подключается в начале этого файла.
> ![Снимок экрана от 2019-12-14 12-37-48](https://user-images.githubusercontent.com/36810364/70846831-93047480-1e6e-11ea-9752-ba5a92c5620f.png)
> Я так понимаю у тебя поэтому везде встречаются по 2 блока на миксин?
> ![Снимок экрана от 2019-12-14 12-45-05](https://user-images.githubusercontent.com/36810364/70846943-af54e100-1e6f-11ea-9e6a-646245f871bf.png)
> 
> Весь код в js писать на классах.

исправил

**Comment by EvgeniyChuprov** [comment]
11. [Выносить обработчики событий в отдельные функции;
![Снимок экрана от 2020-02-24 13-46-23](https://user-images.githubusercontent.com/36810364/75146409-18789080-570c-11ea-8e65-4ba67deaf03c.png)
](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md)
для всех обработчиков.

**Comment by Vodkamishka** [comment]
> 1. [Выносить обработчики событий в отдельные функции;
>    ![Снимок экрана от 2020-02-24 13-46-23](https://user-images.githubusercontent.com/36810364/75146409-18789080-570c-11ea-8e65-4ba67deaf03c.png)
>    ](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md)
>    для всех обработчиков.

исправил
