### ISSUE TITLE
scss

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/hotel-webpack-pug-scss#5]
Заменить px на относительные единицы.

**Comment by EvgeniyChuprov** [comment]
Пиксели до сих пор встречаются, этот не единственный.
![Снимок экрана от 2019-12-23 09-00-48](https://user-images.githubusercontent.com/36810364/71338938-c4fa9280-2562-11ea-82b9-b1a3e0a0e439.png)

Стили применять только к классам
![Снимок экрана от 2019-12-23 09-03-18](https://user-images.githubusercontent.com/36810364/71339025-26226600-2563-11ea-9980-f7df1f80261f.png)

Внешние отступы к блокам применять запрещено
![Снимок экрана от 2019-12-23 09-06-01](https://user-images.githubusercontent.com/36810364/71339116-8c0eed80-2563-11ea-93a0-34dd497b17e0.png)

Позиционирование блока padding-ами так же не рекомендуется. Не известно как поведет себя миксин при помещении его в контейнер другой формы.
![Снимок экрана от 2019-12-23 09-15-31](https://user-images.githubusercontent.com/36810364/71339521-d04ebd80-2564-11ea-92b5-e9584f137098.png)

**Comment by EvgeniyChuprov** [comment]
Установить и настроить eslint по стандартам airbnb

**Comment by Vodkamishka** [comment]
> Заменить px на относительные единицы.

Сделал

**Comment by Vodkamishka** [comment]
> Пиксели до сих пор встречаются. Этот и следующие правки проверить по всему проекту.
> ![Снимок экрана от 2019-12-23 09-00-48](https://user-images.githubusercontent.com/36810364/71338938-c4fa9280-2562-11ea-82b9-b1a3e0a0e439.png)
> 
> Стили применять только к классам
> ![Снимок экрана от 2019-12-23 09-03-18](https://user-images.githubusercontent.com/36810364/71339025-26226600-2563-11ea-9980-f7df1f80261f.png)
> 
> Внешние отступы к блокам применять запрещено
> ![Снимок экрана от 2019-12-23 09-06-01](https://user-images.githubusercontent.com/36810364/71339116-8c0eed80-2563-11ea-93a0-34dd497b17e0.png)
> 
> Позиционирование блока padding-ами так же не рекомендуется. Не известно как поведет себя миксин при помещении его в контейнер другой формы.
> ![Снимок экрана от 2019-12-23 09-15-31](https://user-images.githubusercontent.com/36810364/71339521-d04ebd80-2564-11ea-92b5-e9584f137098.png)

Сделал
