### ISSUE TITLE
pixel perfect

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/hotel-webpack-pug-scss#6]
Поправить UI KIT. Это не все расхождения.
![Снимок экрана от 2019-12-14 12-31-07](https://user-images.githubusercontent.com/36810364/70846763-a82cd380-1e6d-11ea-848c-9022608dd514.png)
![Снимок экрана от 2019-12-14 12-34-26](https://user-images.githubusercontent.com/36810364/70846791-1ec9d100-1e6e-11ea-98fe-d762e76c890e.png)

**Comment by EvgeniyChuprov** [comment]
Не плохо. На всех страницах немного поправить высоту.
![Снимок экрана от 2019-12-17 13-10-21](https://user-images.githubusercontent.com/36810364/70986274-a281f880-20ce-11ea-8ac5-6ddaa5089bc8.png)

**Comment by Vodkamishka** [comment]
> Поправить UI KIT. Это не все расхождения.
> ![Снимок экрана от 2019-12-14 12-31-07](https://user-images.githubusercontent.com/36810364/70846763-a82cd380-1e6d-11ea-848c-9022608dd514.png)
> ![Снимок экрана от 2019-12-14 12-34-26](https://user-images.githubusercontent.com/36810364/70846791-1ec9d100-1e6e-11ea-98fe-d762e76c890e.png)

исправил

**Comment by Vodkamishka** [comment]
> Не плохо. На всех страницах немного поправить высоту.
> ![Снимок экрана от 2019-12-17 13-10-21](https://user-images.githubusercontent.com/36810364/70986274-a281f880-20ce-11ea-8ac5-6ddaa5089bc8.png)

исправил

**Comment by EvgeniyChuprov** [comment]
Остались:
в футере поле email 
![Снимок экрана от 2020-02-24 13-09-27](https://user-images.githubusercontent.com/36810364/75144212-90908780-5707-11ea-848e-94faa56d39b0.png)
и форма регистрации
![Снимок экрана от 2020-02-24 13-15-06](https://user-images.githubusercontent.com/36810364/75144274-b61d9100-5707-11ea-9510-b69aad1bb4fa.png)

**Comment by Vodkamishka** [comment]
> Остались:
> в футере поле email
> ![Снимок экрана от 2020-02-24 13-09-27](https://user-images.githubusercontent.com/36810364/75144212-90908780-5707-11ea-848e-94faa56d39b0.png)
> и форма регистрации
> ![Снимок экрана от 2020-02-24 13-15-06](https://user-images.githubusercontent.com/36810364/75144274-b61d9100-5707-11ea-9510-b69aad1bb4fa.png)

исправил
