### ISSUE TITLE
Различные правки

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/hotel-webpack-pug-scss#7]
Не стоит использовать инлайновые стили.
![Снимок экрана от 2019-12-23 08-55-52](https://user-images.githubusercontent.com/36810364/71338797-3ede4c00-2562-11ea-961f-4f0e3d26d377.png)

**Comment by EvgeniyChuprov** [comment]
Настроить eslint по стандартам airbnb.

**Comment by EvgeniyChuprov** [comment]
Убрать рамку выделения при клике 
![Снимок экрана от 2019-12-23 09-40-58](https://user-images.githubusercontent.com/36810364/71340638-8667d680-2568-11ea-8d22-6282f2952b98.png)

**Comment by EvgeniyChuprov** [comment]
В фигме показано как должны реагировать кнопки и прочие элементы.
Сейчас ни какой реакции нет.
![Снимок экрана от 2019-12-26 12-20-21](https://user-images.githubusercontent.com/36810364/71469428-1f515880-27da-11ea-8645-f946b8e50606.png)

**Comment by EvgeniyChuprov** [comment]
Кнопки применить не работают.
![Peek 2020-01-13 14-39](https://user-images.githubusercontent.com/36810364/72253419-90826f80-3612-11ea-8292-67190e6f22dc.gif)

**Comment by EvgeniyChuprov** [comment]
Не использовать числа в классах.
![Снимок экрана от 2020-01-13 14-34-25](https://user-images.githubusercontent.com/36810364/72253487-b60f7900-3612-11ea-8e50-10b956ed4464.png)

**Comment by EvgeniyChuprov** [comment]
А если элементов будет 100)
![Снимок экрана от 2020-01-13 14-47-02](https://user-images.githubusercontent.com/36810364/72253871-a04e8380-3613-11ea-8c12-91ea0b949d05.png)
Тут лучше циклом пройтись.

**Comment by EvgeniyChuprov** [comment]
![Снимок экрана от 2020-01-13 14-51-40](https://user-images.githubusercontent.com/36810364/72254139-400c1180-3614-11ea-84d3-d9a169183eb9.png)
в английском нет такого слова - diagramma, правильно будет diagram.

**Comment by Vodkamishka** [comment]
> Не стоит использовать инлайновые стили.
> ![Снимок экрана от 2019-12-23 08-55-52](https://user-images.githubusercontent.com/36810364/71338797-3ede4c00-2562-11ea-961f-4f0e3d26d377.png)

Исправил

**Comment by Vodkamishka** [comment]
> Настроить eslint по стандартам airbnb.

Исправил

**Comment by Vodkamishka** [comment]
> Убрать рамку выделения при клике
> ![Снимок экрана от 2019-12-23 09-40-58](https://user-images.githubusercontent.com/36810364/71340638-8667d680-2568-11ea-8d22-6282f2952b98.png)

исправил

**Comment by Vodkamishka** [comment]
> В фигме показано как должны реагировать кнопки и прочие элементы.
> Сейчас ни какой реакции нет.
> ![Снимок экрана от 2019-12-26 12-20-21](https://user-images.githubusercontent.com/36810364/71469428-1f515880-27da-11ea-8645-f946b8e50606.png)

исправил

**Comment by Vodkamishka** [comment]
> Кнопки применить не работают.
> ![Peek 2020-01-13 14-39](https://user-images.githubusercontent.com/36810364/72253419-90826f80-3612-11ea-8292-67190e6f22dc.gif)

исправил

**Comment by Vodkamishka** [comment]
> Не использовать числа в классах.
> ![Снимок экрана от 2020-01-13 14-34-25](https://user-images.githubusercontent.com/36810364/72253487-b60f7900-3612-11ea-8e50-10b956ed4464.png)

исправил

**Comment by Vodkamishka** [comment]
> А если элементов будет 100)
> ![Снимок экрана от 2020-01-13 14-47-02](https://user-images.githubusercontent.com/36810364/72253871-a04e8380-3613-11ea-8c12-91ea0b949d05.png)
> Тут лучше циклом пройтись.
> 
> Кстати в миксин нужно передавать параметры объектом. всех миксинов касается

исправил

**Comment by Vodkamishka** [comment]
> ![Снимок экрана от 2020-01-13 14-51-40](https://user-images.githubusercontent.com/36810364/72254139-400c1180-3614-11ea-84d3-d9a169183eb9.png)
> в английском нет такого слова - diagramma, правильно будет diagram.

исправил
