### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by EvgeniyChuprov** [Vodkamishka/hotel-webpack-pug-scss#8]
![Снимок экрана от 2020-01-15 13-35-40](https://user-images.githubusercontent.com/36810364/72427117-23024a80-379c-11ea-9ba1-2e43279234ba.png)

Как то так правильно делать.
```
mixin room-details (options)
    - let {classHeader, titlesNavbar, log, register, footer, copyright} = options
    .room-details
```

Проверить во всех миксинах.

**Comment by EvgeniyChuprov** [comment]
Деструктуризация по прежнему не выполнена.

**Comment by Vodkamishka** [comment]
> Деструктуризация по прежнему не выполнена.

В каждом миксине, где количество аргументов больше одного, выполнил деструктивное присваивание.
